sudo add-apt-repository universe -y && sudo add-apt-repository ppa:agornostal/ulauncher -y && sudo apt update && sudo apt install ulauncher
flatpak install flathub com.google.Chrome
flatpak install flathub com.slack.Slack
flatpak install flathub org.remmina.Remmina
flatpak install flathub com.visualstudio.code
flatpak install flathub com.jetbrains.PhpStorm
flatpak install flathub com.spotify.Client
flatpak install flathub com.obsproject.Studio
flatpak install flathub org.videolan.VLC
flatpak install flathub net.ankiweb.Anki
flatpak install flathub com.discordapp.Discord
flatpak install flathub org.telegram.desktop
flatpak install flathub io.dbeaver.DBeaverCommunity
flatpak install flathub com.getpostman.Postman
flatpak install flathub net.nokyan.Resources
flatpak install flathub com.github.tchx84.Flatseal
flatpak install flathub com.mattjakeman.ExtensionManager
flatpak install flathub io.gitlab.adhami3310.Impression
flatpak install flathub org.localsend.localsend_app
flatpak install flathub com.jeffser.Alpaca
flatpak install flathub org.gnome.Weather
flatpak install flathub com.calibre_ebook.calibre
flatpak install flathub com.github.xournalpp.xournalpp
flatpak install flathub org.audacityteam.Audacity
flatpak install flathub de.haeckerfelix.Shortwave
